--TouchLayer = require("app.mgClass.TouchLayer")
StartNode = require("app.myClass.StartNode")
--GameScene = require("app.scenes.GameScene")
--Goods = require("app.myClass.Goods")
--Hero = require("app.myClass.Hero")
--Hook = require("app.myClass.Hook")
MainScene = require("app.scenes.MainScene")
--ShopScene = require("app.scenes.ShopScene")